alert("JavaScript разработал - Брендан Эйх")
alert("JavaScript был разработан за 10 дней")
alert("JavaScript появился в 1995 году")
alert("JavaScript - это Java")
alert("Спецификация языка JavaScript называется ECMAScript")